/**
 * PhoenixApprovalQueue — Inline approval queue for the Phoenix Studio
 *
 * Shows pending posts generated by the orchestrator, allowing the user
 * to approve, reject, or edit them without leaving the Studio.
 * This replaces the separate approval page for the common workflow.
 */
import { useState, useCallback } from 'react';
import { cn } from '@/lib/utils';
import {
  Check,
  X,
  Edit3,
  Clock,
  ChevronDown,
  ChevronUp,
  Calendar,
  Eye,
  Send,
  Loader2,
  MoreHorizontal,
  ImageIcon,
  Video,
  FileText,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { toast } from 'sonner';
import { useApprovalQueue } from '@/hooks/useApprovalQueue';

// ── Types ─────────────────────────────────────────────────

interface ApprovalItem {
  id: number;
  title: string;
  status: 'pending' | 'approved' | 'rejected' | 'published';
  mediaType?: 'image' | 'video' | 'carousel' | 'text';
  imageUrl?: string | null;
  copyText?: string | null;
  platform?: string | null;
  scheduledFor?: string | null;
  createdAt: string;
  productNames?: string[];
}

interface PhoenixApprovalQueueProps {
  className?: string;
  compact?: boolean;
  maxItems?: number;
}

// ── Status Badge ──────────────────────────────────────────

function StatusBadge({ status }: { status: ApprovalItem['status'] }) {
  const config = {
    pending: { label: 'Pending', className: 'bg-yellow-500/10 text-yellow-600 border-yellow-500/20' },
    approved: { label: 'Approved', className: 'bg-green-500/10 text-green-600 border-green-500/20' },
    rejected: { label: 'Rejected', className: 'bg-red-500/10 text-red-600 border-red-500/20' },
    published: { label: 'Published', className: 'bg-blue-500/10 text-blue-600 border-blue-500/20' },
  };
  const { label, className } = config[status];
  return (
    <Badge variant="outline" className={cn('text-[10px] font-medium', className)}>
      {label}
    </Badge>
  );
}

// ── Approval Item Card ────────────────────────────────────

function ApprovalItemCard({
  item,
  onApprove,
  onReject,
  onEdit,
  isActioning,
}: {
  item: ApprovalItem;
  onApprove: (id: number) => void;
  onReject: (id: number) => void;
  onEdit: (id: number) => void;
  isActioning: number | null;
}) {
  const [expanded, setExpanded] = useState(false);
  const isLoading = isActioning === item.id;

  const mediaIcon = {
    image: ImageIcon,
    video: Video,
    carousel: ImageIcon,
    text: FileText,
  };
  const MediaIcon = mediaIcon[item.mediaType ?? 'image'] ?? ImageIcon;

  return (
    <div
      className={cn(
        'rounded-lg border border-border/50 bg-card/50 overflow-hidden transition-all',
        expanded && 'ring-1 ring-primary/20',
      )}
    >
      {/* Header row */}
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center gap-2 p-2.5 text-left hover:bg-muted/30 transition-colors"
      >
        {/* Thumbnail */}
        {item.imageUrl ? (
          <img src={item.imageUrl} alt={item.title} className="w-10 h-10 rounded object-cover flex-shrink-0" />
        ) : (
          <div className="w-10 h-10 rounded bg-muted flex items-center justify-center flex-shrink-0">
            <MediaIcon className="w-4 h-4 text-muted-foreground" />
          </div>
        )}

        <div className="flex-1 min-w-0">
          <p className="text-xs font-medium truncate">{item.title}</p>
          <div className="flex items-center gap-1.5 mt-0.5">
            <StatusBadge status={item.status} />
            {item.platform && <span className="text-[10px] text-muted-foreground">{item.platform}</span>}
          </div>
        </div>

        {expanded ? (
          <ChevronUp className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />
        ) : (
          <ChevronDown className="w-3.5 h-3.5 text-muted-foreground flex-shrink-0" />
        )}
      </button>

      {/* Expanded content */}
      {expanded && (
        <div className="px-2.5 pb-2.5 space-y-2 border-t border-border/30">
          {/* Preview */}
          {item.imageUrl && (
            <div className="mt-2 rounded-lg overflow-hidden">
              <img src={item.imageUrl} alt={item.title} className="w-full max-h-48 object-contain bg-muted/20" />
            </div>
          )}

          {/* Copy text */}
          {item.copyText && (
            <div className="bg-muted/20 rounded-lg p-2">
              <p className="text-xs text-muted-foreground line-clamp-4 whitespace-pre-wrap">{item.copyText}</p>
            </div>
          )}

          {/* Product tags */}
          {item.productNames && item.productNames.length > 0 && (
            <div className="flex flex-wrap gap-1">
              {item.productNames.map((name) => (
                <span key={name} className="text-[9px] px-1.5 py-0.5 rounded-full bg-primary/10 text-primary">
                  {name}
                </span>
              ))}
            </div>
          )}

          {/* Schedule info */}
          {item.scheduledFor && (
            <div className="flex items-center gap-1 text-[10px] text-muted-foreground">
              <Calendar className="w-3 h-3" />
              Scheduled:{' '}
              {new Date(item.scheduledFor).toLocaleDateString('en-GB', {
                weekday: 'short',
                day: 'numeric',
                month: 'short',
                hour: '2-digit',
                minute: '2-digit',
              })}
            </div>
          )}

          {/* Action buttons */}
          {item.status === 'pending' && (
            <div className="flex items-center gap-1.5 pt-1">
              <Button
                variant="default"
                size="sm"
                className="h-7 text-xs gap-1 flex-1"
                onClick={() => onApprove(item.id)}
                disabled={isLoading}
              >
                {isLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Check className="w-3 h-3" />}
                Approve
              </Button>
              <Button
                variant="outline"
                size="sm"
                className="h-7 text-xs gap-1"
                onClick={() => onEdit(item.id)}
                disabled={isLoading}
              >
                <Edit3 className="w-3 h-3" />
                Edit
              </Button>
              <Button
                variant="ghost"
                size="sm"
                className="h-7 text-xs gap-1 text-destructive hover:text-destructive"
                onClick={() => onReject(item.id)}
                disabled={isLoading}
              >
                <X className="w-3 h-3" />
              </Button>
            </div>
          )}

          {item.status === 'approved' && (
            <div className="flex items-center gap-1.5 pt-1">
              <Button variant="default" size="sm" className="h-7 text-xs gap-1 flex-1" disabled={isLoading}>
                <Send className="w-3 h-3" />
                Publish Now
              </Button>
              <Button variant="outline" size="sm" className="h-7 text-xs gap-1" disabled={isLoading}>
                <Calendar className="w-3 h-3" />
                Schedule
              </Button>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// ── Main Component ────────────────────────────────────────

export function PhoenixApprovalQueue({ className, compact = false, maxItems = 20 }: PhoenixApprovalQueueProps) {
  const { data, isLoading } = useApprovalQueue();
  const [isActioning, setIsActioning] = useState<number | null>(null);
  const [filter, setFilter] = useState<'all' | 'pending' | 'approved'>('pending');

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const items: ApprovalItem[] =
    (data as any[])?.map((d: any) => ({
      id: d.id,
      title: d.title ?? d.name ?? `Post #${d.id}`,
      status: d.status ?? 'pending',
      mediaType: d.mediaType ?? 'image',
      imageUrl: d.imageUrl ?? d.thumbnailUrl,
      copyText: d.copyText ?? d.caption,
      platform: d.platform,
      scheduledFor: d.scheduledFor ?? d.scheduledDate,
      createdAt: d.createdAt,
      productNames: d.productNames ?? [],
    })) ?? [];

  const filteredItems = items.filter((item) => filter === 'all' || item.status === filter).slice(0, maxItems);

  const pendingCount = items.filter((i) => i.status === 'pending').length;
  const approvedCount = items.filter((i) => i.status === 'approved').length;

  const handleApprove = useCallback(async (id: number) => {
    setIsActioning(id);
    try {
      await fetch(`/api/approval-queue/${id}/approve`, {
        method: 'POST',
        credentials: 'include',
      });
      toast.success('Post approved');
    } catch {
      toast.error('Failed to approve');
    } finally {
      setIsActioning(null);
    }
  }, []);

  const handleReject = useCallback(async (id: number) => {
    setIsActioning(id);
    try {
      await fetch(`/api/approval-queue/${id}/reject`, {
        method: 'POST',
        credentials: 'include',
      });
      toast.success('Post rejected');
    } catch {
      toast.error('Failed to reject');
    } finally {
      setIsActioning(null);
    }
  }, []);

  const handleEdit = useCallback((id: number) => {
    toast.info('Opening editor...', { description: `Editing post #${id}` });
    // TODO: Open the post in the canvas editor
  }, []);

  if (isLoading) {
    return (
      <div className={cn('flex items-center justify-center py-8', className)}>
        <Loader2 className="w-5 h-5 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className={cn('flex flex-col', className)}>
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-border/50">
        <div className="flex items-center gap-2">
          <Clock className="w-4 h-4 text-muted-foreground" />
          <span className="text-sm font-semibold">Approval Queue</span>
          {pendingCount > 0 && (
            <Badge variant="secondary" className="text-[10px] h-4 px-1.5">
              {pendingCount}
            </Badge>
          )}
        </div>
      </div>

      {/* Filter tabs */}
      <div className="flex items-center gap-1 px-3 py-1.5 border-b border-border/30">
        {(['pending', 'approved', 'all'] as const).map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            className={cn(
              'text-[11px] px-2 py-1 rounded-md font-medium transition-colors capitalize',
              filter === f ? 'bg-primary/10 text-primary' : 'text-muted-foreground hover:text-foreground',
            )}
          >
            {f}
            {f === 'pending' && pendingCount > 0 && <span className="ml-1 text-[9px]">({pendingCount})</span>}
            {f === 'approved' && approvedCount > 0 && <span className="ml-1 text-[9px]">({approvedCount})</span>}
          </button>
        ))}
      </div>

      {/* Items */}
      <div className="flex-1 overflow-y-auto p-2 space-y-1.5">
        {filteredItems.length > 0 ? (
          filteredItems.map((item) => (
            <ApprovalItemCard
              key={item.id}
              item={item}
              onApprove={handleApprove}
              onReject={handleReject}
              onEdit={handleEdit}
              isActioning={isActioning}
            />
          ))
        ) : (
          <div className="text-center py-8">
            <Clock className="w-8 h-8 text-muted-foreground/20 mx-auto mb-2" />
            <p className="text-xs text-muted-foreground">
              {filter === 'pending' ? 'No pending posts. Ask Phoenix to generate some!' : 'No posts in this category.'}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}

export default PhoenixApprovalQueue;
