import { createHash } from 'crypto';
import type {
  IdeaBankSuggestion,
  IdeaBankSuggestResponse,
  IdeaBankTemplateResponse,
  TemplateSlotSuggestion,
} from '@shared/types/ideaBank';

export interface FallbackCopyVariation {
  headline: string;
  hook: string;
  bodyText: string;
  cta: string;
  caption: string;
  hashtags: string[];
  framework: string;
  qualityScore: {
    clarity: number;
    persuasiveness: number;
    platformFit: number;
    brandAlignment: number;
    overallScore: number;
    reasoning: string;
  };
  characterCounts: {
    headline: number;
    hook: number;
    body: number;
    caption: number;
    total: number;
  };
}

function cleanText(value: string, fallback: string): string {
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : fallback;
}

function hashToIndex(seed: string, size: number): number {
  const hash = createHash('sha1').update(seed).digest('hex');
  const num = Number.parseInt(hash.slice(0, 8), 16);
  return num % Math.max(size, 1);
}

export function buildFallbackImageUrl(prompt: string, resolution: '1K' | '2K' | '4K' = '2K'): string {
  const sizeMap: Record<'1K' | '2K' | '4K', string> = {
    '1K': '1024x1024',
    '2K': '1536x1536',
    '4K': '2048x2048',
  };
  const shortPrompt = cleanText(prompt, 'Generated Preview').slice(0, 42);
  return `https://placehold.co/${sizeMap[resolution]}/png?text=${encodeURIComponent(shortPrompt)}`;
}

export function buildFallbackIdeaBankResponse(params: {
  userGoal?: string;
  maxSuggestions?: number;
  uploadDescriptions?: string[];
}): IdeaBankSuggestResponse {
  const goal = cleanText(params.userGoal ?? '', 'show practical product benefits on-site');
  const subject = cleanText(params.uploadDescriptions?.[0] ?? '', 'the selected product');
  const limit = Math.min(Math.max(params.maxSuggestions ?? 3, 1), 5);

  const templates = [
    `Wide-angle jobsite scene featuring ${subject} with clear workflow context`,
    `Close-up detail shot of ${subject} highlighting quality and finish`,
    `Before/after install sequence showing how ${subject} improves outcomes`,
    `Technician in-action composition demonstrating ${subject} in real use`,
    `Product + callout overlay design focused on reliability and speed`,
  ];

  const suggestions: IdeaBankSuggestion[] = Array.from({ length: limit }).map((_, i) => {
    const idx = (hashToIndex(`${goal}:${subject}`, templates.length) + i) % templates.length;
    const template = templates[idx] ?? templates[0] ?? 'Professional product campaign visual';
    const prompt = `${template}. Campaign goal: ${goal}. Keep the visual style clean, professional, and realistic.`;
    return {
      id: `fallback-idea-${i + 1}`,
      summary: `Fallback concept ${i + 1}: ${template.slice(0, 60)}`,
      prompt,
      mode: 'standard',
      reasoning: 'Generated by deterministic fallback because AI provider is temporarily unavailable.',
      confidence: Math.max(45, 70 - i * 4),
      sourcesUsed: {
        visionAnalysis: false,
        kbRetrieval: false,
        webSearch: false,
        templateMatching: false,
      },
      recommendedPlatform: 'linkedin',
      recommendedAspectRatio: '1:1',
    };
  });

  return {
    suggestions,
    analysisStatus: {
      visionComplete: false,
      kbQueried: false,
      templatesMatched: 0,
      webSearchUsed: false,
      productKnowledgeUsed: false,
      uploadDescriptionsUsed: params.uploadDescriptions?.length ?? 0,
      learnedPatternsUsed: 0,
    },
  };
}

export function buildFallbackTemplateResponse(params: {
  templateId: string;
  userGoal?: string;
}): IdeaBankTemplateResponse {
  const goal = cleanText(params.userGoal ?? '', 'promote product value');
  const slotSuggestions: TemplateSlotSuggestion[] = [
    {
      productHighlights: ['Durable construction', 'Fast installation', 'Reliable performance'],
      productPlacement: 'Center product in foreground with supporting context in background',
      detailsToEmphasize: ['Material texture', 'Connection points', 'Scale in real environment'],
      headerText: 'Built for Demanding Jobsites',
      bodyText: 'Professional-grade results with faster project turnaround.',
      ctaSuggestion: 'Request Specs',
      colorHarmony: ['industrial gray', 'safety orange', 'neutral white'],
      lightingNotes: 'Use crisp daylight with moderate contrast for material clarity',
      confidence: 58,
      reasoning: 'Deterministic fallback template guidance based on typical construction ad patterns.',
    },
  ];

  return {
    slotSuggestions,
    template: {
      id: params.templateId,
      title: 'Fallback Template',
      category: 'product_showcase',
      promptBlueprint: 'Professional product composition with clear visual hierarchy and practical context.',
    },
    mergedPrompt: `Template fallback prompt: ${goal}. Keep composition clear, realistic, and conversion-focused.`,
    analysisStatus: {
      visionComplete: false,
      kbQueried: false,
      templatesMatched: 1,
      webSearchUsed: false,
      productKnowledgeUsed: false,
      uploadDescriptionsUsed: 0,
      learnedPatternsUsed: 0,
    },
  };
}

export function buildFallbackCopyVariations(params: {
  productName: string;
  productDescription: string;
  platform: string;
  industry: string;
  count: number;
}): FallbackCopyVariation[] {
  const productName = cleanText(params.productName, 'Your product');
  const productDescription = cleanText(params.productDescription, 'Professional solution for demanding teams');
  const industry = cleanText(params.industry, 'your industry');
  const count = Math.min(Math.max(params.count, 1), 5);

  const hooks = [
    `Stop losing time on avoidable ${industry} delays.`,
    `Built for teams that need predictable results every week.`,
    `When deadlines are tight, reliability matters most.`,
    `Give your crew a solution that keeps projects moving.`,
    `A practical upgrade for modern field operations.`,
  ];

  return Array.from({ length: count }).map((_, i) => {
    const hookIdx = (hashToIndex(`${productName}:${productDescription}`, hooks.length) + i) % hooks.length;
    const hook = hooks[hookIdx] ?? hooks[0] ?? `Built for better ${industry} outcomes.`;
    const headline = `${productName} for Real-World Performance`.slice(0, 80);
    const bodyText = `${productDescription} Designed to help teams deliver cleaner installs, fewer callbacks, and better project consistency.`;
    const cta = 'Book a quick demo';
    const caption = `${hook} ${bodyText} ${cta}.`;
    const hashtags = ['#Construction', '#B2BMarketing', '#ProjectEfficiency'];
    const total = headline.length + hook.length + bodyText.length + caption.length;

    return {
      headline,
      hook,
      bodyText,
      cta,
      caption,
      hashtags,
      framework: 'FALLBACK',
      qualityScore: {
        clarity: 7,
        persuasiveness: 6,
        platformFit: 6,
        brandAlignment: 6,
        overallScore: 6,
        reasoning: 'Deterministic fallback copy used while AI provider is unavailable.',
      },
      characterCounts: {
        headline: headline.length,
        hook: hook.length,
        body: bodyText.length,
        caption: caption.length,
        total,
      },
    };
  });
}

export function buildFallbackAnalysisAnswer(params: {
  question: string;
  originalPrompt: string;
  editPrompt?: string | null;
}): string {
  const q = cleanText(params.question, 'How can I improve this output?');
  const original = cleanText(params.originalPrompt, 'the original prompt');
  const edit = cleanText(params.editPrompt ?? '', '');
  const editLine = edit ? `Last edit focus: "${edit}". ` : '';

  return `AI analysis is temporarily unavailable. ${editLine}Based on your prompt "${original}", review composition clarity, product visibility, and CTA readability first. For your question "${q}", prioritize stronger subject contrast, tighter framing, and one clear conversion action.`;
}

export function buildFallbackAgentReply(userMessage: string): string {
  const clean = cleanText(userMessage, 'your request').slice(0, 160);
  return `AI is temporarily unavailable, so I switched to deterministic guidance. For "${clean}", I recommend: 1) lock the primary campaign goal, 2) choose 1-3 products, 3) use a concrete scene prompt with audience + outcome, 4) run generation again once provider health recovers.`;
}
